"A Column Chart"
#Autogenerated by ReportLab guiedit do not edit
from rlextra.graphics.quickchart import QuickChart
from reportlab.lib.corp import white, black
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin
from reportlab.lib.colors import green, red

class Drawing_000(_DrawingEditorMixin,Drawing):
	"""
	Column Chart - with 3 series on a white background
	"""
	def __init__(self,width=400,height=200,*args,**kw):
		Drawing.__init__(self,width,height,*args,**kw)
		self._add(self,QuickChart(),name='chart',validate=None,desc=None)
		self.chart.height               = 200
		self.chart.seriesNames          ='a','b','c'
		self.chart.seriesRelation       = None#
		self.chart.dataLabelsFontSize   = 12
		self.chart.chartSeparation      = 1
		self.chart.data                 = [[100, 120, 140], [110, 130, 150],[200,100,100]]
		self.chart.chartType='column'
		self.chart.titleText            = 'Column Chart'
		self.chart.xTitleText           = ''
		self.chart.categoryNames        = ('2009','2010','2012')
		self.chart.pointerLabelMode     = 'leftAndRight'
		self.chart.bgColor              = 'white'
		self.chart.plotColor            = white
		self.chart.titleFontColor       = black

if __name__=="__main__": #NORUNTESTS
	Drawing_000().save(formats=['pdf'],outDir='.',fnRoot=None)
